export interface Destination {
  id: string;
  name: string;
  country: string;
  capital: string;
  currency: string;
  currencyCode: string;
  language: string;
  voltage: string;
  timezone: string;
  timezoneOffset: number;
  latitude: number;
  longitude: number;
  bestSeason: string;
  visaInfo: string;
  vaccines: string[];
  documentsNeeded: string[];
  continent: string;
  flagEmoji: string;
}

export const destinations: Destination[] = [
  {
    id: 'brasil',
    name: 'Brasil',
    country: 'Brasil',
    capital: 'Brasília',
    currency: 'Real (R$)',
    currencyCode: 'BRL',
    language: 'Português',
    voltage: '127V/220V, 60Hz',
    timezone: 'Mesmo fuso (UTC-3)',
    timezoneOffset: 0,
    latitude: -15.7801,
    longitude: -47.9292,
    bestSeason: 'Ano todo (varia por região)',
    visaInfo: 'Não necessário para brasileiros',
    vaccines: ['Febre Amarela (regiões endêmicas)'],
    documentsNeeded: ['RG ou CNH'],
    continent: 'América do Sul',
    flagEmoji: '🇧🇷',
  },
  {
    id: 'argentina',
    name: 'Argentina',
    country: 'Argentina',
    capital: 'Buenos Aires',
    currency: 'Peso Argentino (ARS)',
    currencyCode: 'ARS',
    language: 'Espanhol',
    voltage: '220V, 50Hz',
    timezone: 'Mesmo fuso (UTC-3)',
    timezoneOffset: 0,
    latitude: -34.6037,
    longitude: -58.3816,
    bestSeason: 'Setembro a Novembro / Março a Maio',
    visaInfo: 'Passaporte ou RG brasileiro',
    vaccines: ['Febre Amarela (recomendada)'],
    documentsNeeded: ['Passaporte ou RG'],
    continent: 'América do Sul',
    flagEmoji: '🇦🇷',
  },
  {
    id: 'chile',
    name: 'Chile',
    country: 'Chile',
    capital: 'Santiago',
    currency: 'Peso Chileno (CLP)',
    currencyCode: 'CLP',
    language: 'Espanhol',
    voltage: '220V, 50Hz',
    timezone: '-1h a -2h (UTC-4/-5)',
    timezoneOffset: -1,
    latitude: -33.4569,
    longitude: -70.6483,
    bestSeason: 'Outubro a Março (Sul) / Ano todo (Norte)',
    visaInfo: 'Passaporte ou RG brasileiro',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte ou RG'],
    continent: 'América do Sul',
    flagEmoji: '🇨🇱',
  },
  {
    id: 'peru',
    name: 'Peru',
    country: 'Peru',
    capital: 'Lima',
    currency: 'Sol Peruano (PEN)',
    currencyCode: 'PEN',
    language: 'Espanhol / Quéchua',
    voltage: '220V, 60Hz',
    timezone: '-2h (UTC-5)',
    timezoneOffset: -2,
    latitude: -12.0464,
    longitude: -77.0428,
    bestSeason: 'Maio a Setembro',
    visaInfo: 'Passaporte válido (RG aceito em alguns casos)',
    vaccines: ['Febre Amarela (regiões amazônicas)'],
    documentsNeeded: ['Passaporte'],
    continent: 'América do Sul',
    flagEmoji: '🇵🇪',
  },
  {
    id: 'colombia',
    name: 'Colômbia',
    country: 'Colômbia',
    capital: 'Bogotá',
    currency: 'Peso Colombiano (COP)',
    currencyCode: 'COP',
    language: 'Espanhol',
    voltage: '110V, 60Hz',
    timezone: '-2h (UTC-5)',
    timezoneOffset: -2,
    latitude: 4.7110,
    longitude: -74.0721,
    bestSeason: 'Dezembro a Março / Julho a Agosto',
    visaInfo: 'Passaporte ou RG brasileiro',
    vaccines: ['Febre Amarela (regiões amazônicas)'],
    documentsNeeded: ['Passaporte ou RG'],
    continent: 'América do Sul',
    flagEmoji: '🇨🇴',
  },
  {
    id: 'mexico',
    name: 'México',
    country: 'México',
    capital: 'Cidade do México',
    currency: 'Peso Mexicano (MXN)',
    currencyCode: 'MXN',
    language: 'Espanhol',
    voltage: '127V, 60Hz',
    timezone: '-3h a -5h (varia)',
    timezoneOffset: -3,
    latitude: 19.4326,
    longitude: -99.1332,
    bestSeason: 'Novembro a Abril',
    visaInfo: 'Passaporte válido (sem visto)',
    vaccines: ['Hepatite A', 'Tifoide (recomendadas)'],
    documentsNeeded: ['Passaporte'],
    continent: 'América Central',
    flagEmoji: '🇲🇽',
  },
  {
    id: 'usa-nyc',
    name: 'Nova York (EUA)',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    currency: 'Dólar Americano (USD)',
    currencyCode: 'USD',
    language: 'Inglês',
    voltage: '120V, 60Hz',
    timezone: '-2h (UTC-5)',
    timezoneOffset: -2,
    latitude: 40.7128,
    longitude: -74.0060,
    bestSeason: 'Abril a Junho / Setembro a Novembro',
    visaInfo: 'Visto americano (B1/B2) obrigatório',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Visto Americano (B1/B2)', 'ESTA'],
    continent: 'América do Norte',
    flagEmoji: '🇺🇸',
  },
  {
    id: 'usa-miami',
    name: 'Miami (EUA)',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    currency: 'Dólar Americano (USD)',
    currencyCode: 'USD',
    language: 'Inglês / Espanhol',
    voltage: '120V, 60Hz',
    timezone: '-2h (UTC-5)',
    timezoneOffset: -2,
    latitude: 25.7617,
    longitude: -80.1918,
    bestSeason: 'Novembro a Abril',
    visaInfo: 'Visto americano (B1/B2) obrigatório',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Visto Americano (B1/B2)'],
    continent: 'América do Norte',
    flagEmoji: '🇺🇸',
  },
  {
    id: 'usa-orlando',
    name: 'Orlando (EUA)',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    currency: 'Dólar Americano (USD)',
    currencyCode: 'USD',
    language: 'Inglês',
    voltage: '120V, 60Hz',
    timezone: '-2h (UTC-5)',
    timezoneOffset: -2,
    latitude: 28.5383,
    longitude: -81.3792,
    bestSeason: 'Janeiro a Abril / Setembro a Novembro',
    visaInfo: 'Visto americano (B1/B2) obrigatório',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Visto Americano (B1/B2)'],
    continent: 'América do Norte',
    flagEmoji: '🇺🇸',
  },
  {
    id: 'usa-la',
    name: 'Los Angeles (EUA)',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    currency: 'Dólar Americano (USD)',
    currencyCode: 'USD',
    language: 'Inglês',
    voltage: '120V, 60Hz',
    timezone: '-5h (UTC-8)',
    timezoneOffset: -5,
    latitude: 34.0522,
    longitude: -118.2437,
    bestSeason: 'Março a Maio / Setembro a Novembro',
    visaInfo: 'Visto americano (B1/B2) obrigatório',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Visto Americano (B1/B2)'],
    continent: 'América do Norte',
    flagEmoji: '🇺🇸',
  },
  {
    id: 'usa-vegas',
    name: 'Las Vegas (EUA)',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    currency: 'Dólar Americano (USD)',
    currencyCode: 'USD',
    language: 'Inglês',
    voltage: '120V, 60Hz',
    timezone: '-6h (UTC-9)',
    timezoneOffset: -6,
    latitude: 36.1699,
    longitude: -115.1398,
    bestSeason: 'Março a Maio / Setembro a Novembro',
    visaInfo: 'Visto americano (B1/B2) obrigatório',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Visto Americano (B1/B2)'],
    continent: 'América do Norte',
    flagEmoji: '🇺🇸',
  },
  {
    id: 'canada',
    name: 'Canadá',
    country: 'Canadá',
    capital: 'Ottawa',
    currency: 'Dólar Canadense (CAD)',
    currencyCode: 'CAD',
    language: 'Inglês / Francês',
    voltage: '120V, 60Hz',
    timezone: '-2h a -5h (varia)',
    timezoneOffset: -2,
    latitude: 45.4215,
    longitude: -75.6972,
    bestSeason: 'Junho a Setembro / Dezembro a Março (ski)',
    visaInfo: 'eTA obrigatória',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'eTA (Autorização Eletrônica de Viagem)'],
    continent: 'América do Norte',
    flagEmoji: '🇨🇦',
  },
  {
    id: 'cuba',
    name: 'Cuba',
    country: 'Cuba',
    capital: 'Havana',
    currency: 'Peso Cubano (CUP)',
    currencyCode: 'CUP',
    language: 'Espanhol',
    voltage: '110V/220V, 60Hz',
    timezone: '-2h (UTC-5)',
    timezoneOffset: -2,
    latitude: 23.1136,
    longitude: -82.3666,
    bestSeason: 'Novembro a Abril',
    visaInfo: 'Cartão de turista (Tourist Card)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Cartão de Turista', 'Seguro de saúde'],
    continent: 'Caribe',
    flagEmoji: '🇨🇺',
  },
  {
    id: 'uruguay',
    name: 'Uruguai',
    country: 'Uruguai',
    capital: 'Montevidéu',
    currency: 'Peso Uruguaio (UYU)',
    currencyCode: 'UYU',
    language: 'Espanhol',
    voltage: '220V, 50Hz',
    timezone: 'Mesmo fuso (UTC-3)',
    timezoneOffset: 0,
    latitude: -34.9011,
    longitude: -56.1645,
    bestSeason: 'Dezembro a Março',
    visaInfo: 'Passaporte ou RG brasileiro',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte ou RG'],
    continent: 'América do Sul',
    flagEmoji: '🇺🇾',
  },
  {
    id: 'portugal',
    name: 'Portugal',
    country: 'Portugal',
    capital: 'Lisboa',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Português',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 38.7223,
    longitude: -9.1393,
    bestSeason: 'Abril a Outubro',
    visaInfo: 'Passaporte válido (brasileiros: isenção de visto até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Europa',
    flagEmoji: '🇵🇹',
  },
  {
    id: 'espanha',
    name: 'Espanha',
    country: 'Espanha',
    capital: 'Madrid',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Espanhol',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 40.4168,
    longitude: -3.7038,
    bestSeason: 'Abril a Junho / Setembro a Outubro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇪🇸',
  },
  {
    id: 'franca',
    name: 'França',
    country: 'França',
    capital: 'Paris',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Francês',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 48.8566,
    longitude: 2.3522,
    bestSeason: 'Abril a Junho / Setembro a Outubro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇫🇷',
  },
  {
    id: 'italia',
    name: 'Itália',
    country: 'Itália',
    capital: 'Roma',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Italiano',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 41.9028,
    longitude: 12.4964,
    bestSeason: 'Abril a Junho / Setembro a Outubro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇮🇹',
  },
  {
    id: 'inglaterra',
    name: 'Inglaterra',
    country: 'Reino Unido',
    capital: 'Londres',
    currency: 'Libra Esterlina (£)',
    currencyCode: 'GBP',
    language: 'Inglês',
    voltage: '230V, 50Hz',
    timezone: '+3h (UTC+0)',
    timezoneOffset: 3,
    latitude: 51.5074,
    longitude: -0.1278,
    bestSeason: 'Maio a Setembro',
    visaInfo: 'Visto do Reino Unido obrigatório para brasileiros',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Visto do Reino Unido'],
    continent: 'Europa',
    flagEmoji: '🇬🇧',
  },
  {
    id: 'alemanha',
    name: 'Alemanha',
    country: 'Alemanha',
    capital: 'Berlim',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Alemão',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 52.5200,
    longitude: 13.4050,
    bestSeason: 'Maio a Setembro / Dezembro (mercados natalinos)',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇩🇪',
  },
  {
    id: 'holanda',
    name: 'Holanda',
    country: 'Países Baixos',
    capital: 'Amsterdã',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Holandês',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 52.3676,
    longitude: 4.9041,
    bestSeason: 'Abril a Outubro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇳🇱',
  },
  {
    id: 'grecia',
    name: 'Grécia',
    country: 'Grécia',
    capital: 'Atenas',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Grego',
    voltage: '230V, 50Hz',
    timezone: '+5h (UTC+2)',
    timezoneOffset: 5,
    latitude: 37.9838,
    longitude: 23.7275,
    bestSeason: 'Maio a Outubro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇬🇷',
  },
  {
    id: 'suica',
    name: 'Suíça',
    country: 'Suíça',
    capital: 'Berna',
    currency: 'Franco Suíço (CHF)',
    currencyCode: 'CHF',
    language: 'Alemão / Francês / Italiano',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 46.9481,
    longitude: 7.4474,
    bestSeason: 'Julho a Setembro / Dezembro a Março (ski)',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇨🇭',
  },
  {
    id: 'austria',
    name: 'Áustria',
    country: 'Áustria',
    capital: 'Viena',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Alemão',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 48.2082,
    longitude: 16.3738,
    bestSeason: 'Maio a Setembro / Dezembro a Março',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇦🇹',
  },
  {
    id: 'irlanda',
    name: 'Irlanda',
    country: 'Irlanda',
    capital: 'Dublin',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Inglês / Irlandês',
    voltage: '230V, 50Hz',
    timezone: '+3h (UTC+0)',
    timezoneOffset: 3,
    latitude: 53.3498,
    longitude: -6.2603,
    bestSeason: 'Maio a Setembro',
    visaInfo: 'Passaporte válido (sem visto até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Europa',
    flagEmoji: '🇮🇪',
  },
  {
    id: 'croacia',
    name: 'Croácia',
    country: 'Croácia',
    capital: 'Zagreb',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Croata',
    voltage: '230V, 50Hz',
    timezone: '+5h (UTC+2)',
    timezoneOffset: 5,
    latitude: 45.8150,
    longitude: 15.9819,
    bestSeason: 'Junho a Setembro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇭🇷',
  },
  {
    id: 'republica-tcheca',
    name: 'República Tcheca',
    country: 'República Tcheca',
    capital: 'Praga',
    currency: 'Coroa Tcheca (CZK)',
    currencyCode: 'CZK',
    language: 'Tcheco',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 50.0755,
    longitude: 14.4378,
    bestSeason: 'Maio a Setembro / Dezembro (mercados natalinos)',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇨🇿',
  },
  {
    id: 'turquia',
    name: 'Turquia',
    country: 'Turquia',
    capital: 'Ancara',
    currency: 'Lira Turca (TRY)',
    currencyCode: 'TRY',
    language: 'Turco',
    voltage: '230V, 50Hz',
    timezone: '+6h (UTC+3)',
    timezoneOffset: 6,
    latitude: 39.9334,
    longitude: 32.8597,
    bestSeason: 'Abril a Junho / Setembro a Novembro',
    visaInfo: 'e-Visto obrigatório para brasileiros',
    vaccines: ['Hepatite A', 'Tifoide (recomendadas)'],
    documentsNeeded: ['Passaporte', 'e-Visto Turquia'],
    continent: 'Europa/Ásia',
    flagEmoji: '🇹🇷',
  },
  {
    id: 'noruega',
    name: 'Noruega',
    country: 'Noruega',
    capital: 'Oslo',
    currency: 'Coroa Norueguesa (NOK)',
    currencyCode: 'NOK',
    language: 'Norueguês',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 59.9139,
    longitude: 10.7522,
    bestSeason: 'Junho a Agosto (sol) / Novembro a Fevereiro (aurora)',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇳🇴',
  },
  {
    id: 'islandia',
    name: 'Islândia',
    country: 'Islândia',
    capital: 'Reykjavik',
    currency: 'Coroa Islandesa (ISK)',
    currencyCode: 'ISK',
    language: 'Islandês',
    voltage: '230V, 50Hz',
    timezone: '+3h (UTC+0)',
    timezoneOffset: 3,
    latitude: 64.1466,
    longitude: -21.9426,
    bestSeason: 'Junho a Agosto (verão) / Setembro a Março (aurora boreal)',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇮🇸',
  },
  {
    id: 'belgica',
    name: 'Bélgica',
    country: 'Bélgica',
    capital: 'Bruxelas',
    currency: 'Euro (€)',
    currencyCode: 'EUR',
    language: 'Francês / Holandês / Alemão',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 50.8503,
    longitude: 4.3517,
    bestSeason: 'Abril a Outubro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇧🇪',
  },
  {
    id: 'hungria',
    name: 'Hungria',
    country: 'Hungria',
    capital: 'Budapeste',
    currency: 'Forint Húngaro (HUF)',
    currencyCode: 'HUF',
    language: 'Húngaro',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 47.4979,
    longitude: 19.0402,
    bestSeason: 'Abril a Outubro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇭🇺',
  },
  {
    id: 'polonia',
    name: 'Polônia',
    country: 'Polônia',
    capital: 'Varsóvia',
    currency: 'Zloty Polaco (PLN)',
    currencyCode: 'PLN',
    language: 'Polonês',
    voltage: '230V, 50Hz',
    timezone: '+4h (UTC+1)',
    timezoneOffset: 4,
    latitude: 52.2297,
    longitude: 21.0122,
    bestSeason: 'Maio a Setembro',
    visaInfo: 'Passaporte válido (sem visto Schengen até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido (Schengen)'],
    continent: 'Europa',
    flagEmoji: '🇵🇱',
  },
  {
    id: 'escocia',
    name: 'Escócia',
    country: 'Reino Unido',
    capital: 'Edimburgo',
    currency: 'Libra Esterlina (£)',
    currencyCode: 'GBP',
    language: 'Inglês / Gaélico',
    voltage: '230V, 50Hz',
    timezone: '+3h (UTC+0)',
    timezoneOffset: 3,
    latitude: 55.9533,
    longitude: -3.1883,
    bestSeason: 'Maio a Setembro',
    visaInfo: 'Visto do Reino Unido obrigatório para brasileiros',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'Visto do Reino Unido'],
    continent: 'Europa',
    flagEmoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  },
  {
    id: 'japao',
    name: 'Japão',
    country: 'Japão',
    capital: 'Tóquio',
    currency: 'Iene Japonês (JPY)',
    currencyCode: 'JPY',
    language: 'Japonês',
    voltage: '100V, 50/60Hz',
    timezone: '+12h (UTC+9)',
    timezoneOffset: 12,
    latitude: 35.6762,
    longitude: 139.6503,
    bestSeason: 'Março a Maio (cerejeiras) / Outubro a Novembro (folhas)',
    visaInfo: 'Sem visto para brasileiros (até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Ásia',
    flagEmoji: '🇯🇵',
  },
  {
    id: 'tailandia',
    name: 'Tailândia',
    country: 'Tailândia',
    capital: 'Bangkok',
    currency: 'Baht Tailandês (THB)',
    currencyCode: 'THB',
    language: 'Tailandês',
    voltage: '220V, 50Hz',
    timezone: '+10h (UTC+7)',
    timezoneOffset: 10,
    latitude: 13.7563,
    longitude: 100.5018,
    bestSeason: 'Novembro a Abril',
    visaInfo: 'Sem visto para brasileiros (até 30 dias)',
    vaccines: ['Febre Amarela (exigida se vindo de países endêmicos)', 'Hepatite A', 'Tifoide'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Ásia',
    flagEmoji: '🇹🇭',
  },
  {
    id: 'bali',
    name: 'Bali (Indonésia)',
    country: 'Indonésia',
    capital: 'Jacarta',
    currency: 'Rupia Indonésia (IDR)',
    currencyCode: 'IDR',
    language: 'Indonésio / Balinês',
    voltage: '230V, 50Hz',
    timezone: '+11h (UTC+8)',
    timezoneOffset: 11,
    latitude: -8.4095,
    longitude: 115.1889,
    bestSeason: 'Maio a Setembro',
    visaInfo: 'Visto na chegada (Visa on Arrival) - USD 35',
    vaccines: ['Febre Amarela (se vindo de países endêmicos)', 'Hepatite A', 'Tifoide'],
    documentsNeeded: ['Passaporte', 'Visto on Arrival'],
    continent: 'Ásia',
    flagEmoji: '🇮🇩',
  },
  {
    id: 'vietna',
    name: 'Vietnã',
    country: 'Vietnã',
    capital: 'Hanói',
    currency: 'Dong Vietnamita (VND)',
    currencyCode: 'VND',
    language: 'Vietnamita',
    voltage: '220V, 50Hz',
    timezone: '+10h (UTC+7)',
    timezoneOffset: 10,
    latitude: 21.0285,
    longitude: 105.8542,
    bestSeason: 'Outubro a Abril (Norte) / Ano todo (Sul)',
    visaInfo: 'e-Visto obrigatório para brasileiros',
    vaccines: ['Hepatite A', 'Tifoide', 'Febre Amarela (se vindo de países endêmicos)'],
    documentsNeeded: ['Passaporte', 'e-Visto Vietnã'],
    continent: 'Ásia',
    flagEmoji: '🇻🇳',
  },
  {
    id: 'india',
    name: 'Índia',
    country: 'Índia',
    capital: 'Nova Delhi',
    currency: 'Rupia Indiana (INR)',
    currencyCode: 'INR',
    language: 'Hindi / Inglês',
    voltage: '230V, 50Hz',
    timezone: '+8,5h (UTC+5:30)',
    timezoneOffset: 8.5,
    latitude: 28.6139,
    longitude: 77.2090,
    bestSeason: 'Outubro a Março',
    visaInfo: 'e-Visto obrigatório para brasileiros',
    vaccines: ['Febre Amarela (exigida se vindo de países endêmicos)', 'Hepatite A', 'Tifoide', 'Febre Tifóide'],
    documentsNeeded: ['Passaporte', 'e-Visto Índia'],
    continent: 'Ásia',
    flagEmoji: '🇮🇳',
  },
  {
    id: 'china',
    name: 'China',
    country: 'China',
    capital: 'Pequim',
    currency: 'Yuan Chinês (CNY)',
    currencyCode: 'CNY',
    language: 'Mandarim',
    voltage: '220V, 50Hz',
    timezone: '+11h (UTC+8)',
    timezoneOffset: 11,
    latitude: 39.9042,
    longitude: 116.4074,
    bestSeason: 'Março a Maio / Setembro a Novembro',
    visaInfo: 'Visto chinês obrigatório para brasileiros (exceto trânsito 72h)',
    vaccines: ['Hepatite A', 'Tifoide (recomendadas)'],
    documentsNeeded: ['Passaporte', 'Visto Chinês'],
    continent: 'Ásia',
    flagEmoji: '🇨🇳',
  },
  {
    id: 'coreia-sul',
    name: 'Coreia do Sul',
    country: 'Coreia do Sul',
    capital: 'Seul',
    currency: 'Won Sul-coreano (KRW)',
    currencyCode: 'KRW',
    language: 'Coreano',
    voltage: '220V, 60Hz',
    timezone: '+12h (UTC+9)',
    timezoneOffset: 12,
    latitude: 37.5665,
    longitude: 126.9780,
    bestSeason: 'Março a Maio / Setembro a Novembro',
    visaInfo: 'Sem visto para brasileiros (até 90 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Ásia',
    flagEmoji: '🇰🇷',
  },
  {
    id: 'singapura',
    name: 'Singapura',
    country: 'Singapura',
    capital: 'Singapura',
    currency: 'Dólar de Singapura (SGD)',
    currencyCode: 'SGD',
    language: 'Inglês / Mandarim / Malaio / Tamil',
    voltage: '230V, 50Hz',
    timezone: '+11h (UTC+8)',
    timezoneOffset: 11,
    latitude: 1.3521,
    longitude: 103.8198,
    bestSeason: 'Fevereiro a Abril / Julho a Setembro',
    visaInfo: 'Sem visto para brasileiros (até 30 dias)',
    vaccines: ['Febre Amarela (exigida se vindo de países endêmicos)'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Ásia',
    flagEmoji: '🇸🇬',
  },
  {
    id: 'dubai',
    name: 'Dubai (Emirados Árabes)',
    country: 'Emirados Árabes Unidos',
    capital: 'Abu Dhabi',
    currency: 'Dirham dos Emirados (AED)',
    currencyCode: 'AED',
    language: 'Árabe / Inglês',
    voltage: '220V, 50Hz',
    timezone: '+7h (UTC+4)',
    timezoneOffset: 7,
    latitude: 25.2048,
    longitude: 55.2708,
    bestSeason: 'Outubro a Abril',
    visaInfo: 'Sem visto para brasileiros (até 30 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Oriente Médio',
    flagEmoji: '🇦🇪',
  },
  {
    id: 'israel',
    name: 'Israel',
    country: 'Israel',
    capital: 'Jerusalém / Tel Aviv',
    currency: 'Novo Shekel Israelense (ILS)',
    currencyCode: 'ILS',
    language: 'Hebraico / Árabe',
    voltage: '230V, 50Hz',
    timezone: '+6h (UTC+3)',
    timezoneOffset: 6,
    latitude: 31.7683,
    longitude: 35.2137,
    bestSeason: 'Março a Maio / Setembro a Novembro',
    visaInfo: 'Sem visto para brasileiros (até 90 dias)',
    vaccines: ['Hepatite A', 'Tifoide (recomendadas)'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'Oriente Médio',
    flagEmoji: '🇮🇱',
  },
  {
    id: 'maldivas',
    name: 'Maldivas',
    country: 'Maldivas',
    capital: 'Malé',
    currency: 'Rufiyaa Maldiva (MVR)',
    currencyCode: 'MVR',
    language: 'Dhivehi / Inglês',
    voltage: '230V, 50Hz',
    timezone: '+8h (UTC+5)',
    timezoneOffset: 8,
    latitude: 3.2028,
    longitude: 73.2207,
    bestSeason: 'Novembro a Abril',
    visaInfo: 'Visto gratuito na chegada (30 dias)',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte válido', 'Reserva de hotel confirmada'],
    continent: 'Oceano Índico',
    flagEmoji: '🇲🇻',
  },
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    country: 'Sri Lanka',
    capital: 'Colombo',
    currency: 'Rupia do Sri Lanka (LKR)',
    currencyCode: 'LKR',
    language: 'Cingalês / Tamil / Inglês',
    voltage: '230V, 50Hz',
    timezone: '+8,5h (UTC+5:30)',
    timezoneOffset: 8.5,
    latitude: 7.8731,
    longitude: 80.7718,
    bestSeason: 'Dezembro a Março (Oeste/Sul) / Julho a Setembro (Leste)',
    visaInfo: 'e-Visto obrigatório para brasileiros (ETA)',
    vaccines: ['Febre Amarela (se vindo de países endêmicos)', 'Hepatite A'],
    documentsNeeded: ['Passaporte', 'ETA Sri Lanka'],
    continent: 'Ásia',
    flagEmoji: '🇱🇰',
  },
  {
    id: 'marrocos',
    name: 'Marrocos',
    country: 'Marrocos',
    capital: 'Rabat',
    currency: 'Dirham Marroquino (MAD)',
    currencyCode: 'MAD',
    language: 'Árabe / Francês / Berbere',
    voltage: '220V, 50Hz',
    timezone: '+3h (UTC+0/+1)',
    timezoneOffset: 3,
    latitude: 31.7917,
    longitude: -7.0926,
    bestSeason: 'Março a Maio / Setembro a Novembro',
    visaInfo: 'Sem visto para brasileiros (até 90 dias)',
    vaccines: ['Hepatite A', 'Tifoide (recomendadas)'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'África',
    flagEmoji: '🇲🇦',
  },
  {
    id: 'egito',
    name: 'Egito',
    country: 'Egito',
    capital: 'Cairo',
    currency: 'Libra Egípcia (EGP)',
    currencyCode: 'EGP',
    language: 'Árabe',
    voltage: '220V, 50Hz',
    timezone: '+6h (UTC+3)',
    timezoneOffset: 6,
    latitude: 30.0444,
    longitude: 31.2357,
    bestSeason: 'Outubro a Abril',
    visaInfo: 'Visto na chegada (USD 25) ou e-Visto',
    vaccines: ['Hepatite A', 'Tifoide (recomendadas)'],
    documentsNeeded: ['Passaporte', 'Visto (on arrival ou e-Visto)'],
    continent: 'África',
    flagEmoji: '🇪🇬',
  },
  {
    id: 'africa-do-sul',
    name: 'África do Sul',
    country: 'África do Sul',
    capital: 'Pretória / Cidade do Cabo',
    currency: 'Rand Sul-Africano (ZAR)',
    currencyCode: 'ZAR',
    language: 'Inglês / Afrikaans / Zulu (11 oficiais)',
    voltage: '230V, 50Hz',
    timezone: '+6h (UTC+3 / +2)',
    timezoneOffset: 5,
    latitude: -25.7479,
    longitude: 28.2293,
    bestSeason: 'Outubro a Abril (verão austral)',
    visaInfo: 'Sem visto para brasileiros (até 90 dias)',
    vaccines: ['Febre Amarela (exigida se vindo de países endêmicos)', 'Malária (profilaxia recomendada)'],
    documentsNeeded: ['Passaporte válido'],
    continent: 'África',
    flagEmoji: '🇿🇦',
  },
  {
    id: 'quenia',
    name: 'Quênia',
    country: 'Quênia',
    capital: 'Nairóbi',
    currency: 'Xelim Queniano (KES)',
    currencyCode: 'KES',
    language: 'Suaíli / Inglês',
    voltage: '240V, 50Hz',
    timezone: '+6h (UTC+3)',
    timezoneOffset: 6,
    latitude: -1.2921,
    longitude: 36.8219,
    bestSeason: 'Janeiro a Março / Junho a Outubro (safáris)',
    visaInfo: 'e-Visto obrigatório para brasileiros',
    vaccines: ['Febre Amarela (obrigatória)', 'Malária (profilaxia obrigatória)', 'Hepatite A'],
    documentsNeeded: ['Passaporte', 'e-Visto Quênia', 'Comprovante vacina Febre Amarela'],
    continent: 'África',
    flagEmoji: '🇰🇪',
  },
  {
    id: 'tanzania',
    name: 'Tanzânia',
    country: 'Tanzânia',
    capital: 'Dodoma',
    currency: 'Xelim Tanzaniano (TZS)',
    currencyCode: 'TZS',
    language: 'Suaíli / Inglês',
    voltage: '230V, 50Hz',
    timezone: '+6h (UTC+3)',
    timezoneOffset: 6,
    latitude: -6.7924,
    longitude: 39.2083,
    bestSeason: 'Junho a Outubro (safáris) / Dezembro a Março (Zanzibar)',
    visaInfo: 'Visto obrigatório (on arrival ou e-Visto)',
    vaccines: ['Febre Amarela (obrigatória)', 'Malária (profilaxia obrigatória)', 'Hepatite A'],
    documentsNeeded: ['Passaporte', 'Visto Tanzânia', 'Comprovante vacina Febre Amarela'],
    continent: 'África',
    flagEmoji: '🇹🇿',
  },
  {
    id: 'australia',
    name: 'Austrália',
    country: 'Austrália',
    capital: 'Camberra',
    currency: 'Dólar Australiano (AUD)',
    currencyCode: 'AUD',
    language: 'Inglês',
    voltage: '230V, 50Hz',
    timezone: '+11h a +13h (varia)',
    timezoneOffset: 11,
    latitude: -35.2809,
    longitude: 149.1300,
    bestSeason: 'Setembro a Novembro / Março a Maio',
    visaInfo: 'eVisitor (651) obrigatório - gratuito online',
    vaccines: ['Nenhuma obrigatória (mas recomendadas)'],
    documentsNeeded: ['Passaporte', 'eVisitor Austrália (651)'],
    continent: 'Oceania',
    flagEmoji: '🇦🇺',
  },
  {
    id: 'nova-zelandia',
    name: 'Nova Zelândia',
    country: 'Nova Zelândia',
    capital: 'Wellington',
    currency: 'Dólar Neozelandês (NZD)',
    currencyCode: 'NZD',
    language: 'Inglês / Māori',
    voltage: '230V, 50Hz',
    timezone: '+15h (UTC+12)',
    timezoneOffset: 15,
    latitude: -41.2865,
    longitude: 174.7762,
    bestSeason: 'Dezembro a Março',
    visaInfo: 'NZeTA obrigatória para brasileiros',
    vaccines: ['Nenhuma obrigatória'],
    documentsNeeded: ['Passaporte', 'NZeTA (Nova Zelândia Electronic Travel Authority)'],
    continent: 'Oceania',
    flagEmoji: '🇳🇿',
  },
];

export function getDestinationById(id: string): Destination | undefined {
  return destinations.find((d) => d.id === id);
}

export function getDestinationByName(name: string): Destination | undefined {
  return destinations.find(
    (d) => d.name.toLowerCase() === name.toLowerCase() ||
           d.country.toLowerCase() === name.toLowerCase()
  );
}
