import type { Destination } from './types'

export const DESTINATIONS: Destination[] = [
  // ===== BRASIL =====
  {
    name: 'Brasil – Rio de Janeiro',
    country: 'Brasil',
    capital: 'Rio de Janeiro',
    language: 'Português',
    currency: 'BRL (Real)',
    voltage: '127V / 220V',
    timezone_offset: 0,
    best_season: 'Março a Junho / Agosto a Outubro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto',
    vaccines: [],
    documents_needed: ['RG ou Passaporte'],
    latitude: -22.9068,
    longitude: -43.1729,
  },
  {
    name: 'Brasil – São Paulo',
    country: 'Brasil',
    capital: 'São Paulo',
    language: 'Português',
    currency: 'BRL (Real)',
    voltage: '127V / 220V',
    timezone_offset: 0,
    best_season: 'Março a Maio / Setembro a Novembro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto',
    vaccines: [],
    documents_needed: ['RG ou Passaporte'],
    latitude: -23.5505,
    longitude: -46.6333,
  },
  // ===== ARGENTINA =====
  {
    name: 'Argentina – Buenos Aires',
    country: 'Argentina',
    capital: 'Buenos Aires',
    language: 'Espanhol',
    currency: 'ARS (Peso Argentino)',
    voltage: '220V',
    timezone_offset: 0,
    best_season: 'Setembro a Novembro / Março a Maio',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto',
    vaccines: [],
    documents_needed: ['RG ou Passaporte'],
    latitude: -34.6037,
    longitude: -58.3816,
  },
  // ===== CHILE =====
  {
    name: 'Chile – Santiago',
    country: 'Chile',
    capital: 'Santiago',
    language: 'Espanhol',
    currency: 'CLP (Peso Chileno)',
    voltage: '220V',
    timezone_offset: 0,
    best_season: 'Outubro a Abril',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: -33.4489,
    longitude: -70.6693,
  },
  // ===== PERU =====
  {
    name: 'Peru – Cusco / Machu Picchu',
    country: 'Peru',
    capital: 'Lima',
    language: 'Espanhol / Quechua',
    currency: 'PEN (Sol Peruano)',
    voltage: '220V',
    timezone_offset: -2,
    best_season: 'Maio a Outubro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 183 dias)',
    vaccines: ['Febre Amarela (recomendada)'],
    documents_needed: ['Passaporte válido'],
    latitude: -13.5319,
    longitude: -71.9675,
  },
  // ===== COLÔMBIA =====
  {
    name: 'Colômbia – Cartagena',
    country: 'Colômbia',
    capital: 'Bogotá',
    language: 'Espanhol',
    currency: 'COP (Peso Colombiano)',
    voltage: '110V',
    timezone_offset: -2,
    best_season: 'Dezembro a Abril',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 90 dias)',
    vaccines: ['Febre Amarela (recomendada)'],
    documents_needed: ['Passaporte válido'],
    latitude: 10.3932,
    longitude: -75.4832,
  },
  // ===== MÉXICO =====
  {
    name: 'México – Cancún',
    country: 'México',
    capital: 'Cidade do México',
    language: 'Espanhol',
    currency: 'MXN (Peso Mexicano)',
    voltage: '127V',
    timezone_offset: -2,
    best_season: 'Novembro a Abril',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 180 dias)',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Formulário de Migração (FMM)'],
    latitude: 21.1619,
    longitude: -86.8515,
  },
  // ===== EUA =====
  {
    name: 'EUA – Nova York',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    language: 'Inglês',
    currency: 'USD (Dólar Americano)',
    voltage: '120V',
    timezone_offset: -2,
    best_season: 'Abril a Junho / Setembro a Novembro',
    visa_required: true,
    visa_info: 'Visto B1/B2 obrigatório ou ESTA não disponível para brasileiros',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Visto americano'],
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    name: 'EUA – Miami',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    language: 'Inglês',
    currency: 'USD (Dólar Americano)',
    voltage: '120V',
    timezone_offset: -2,
    best_season: 'Novembro a Abril',
    visa_required: true,
    visa_info: 'Visto B1/B2 obrigatório',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Visto americano'],
    latitude: 25.7617,
    longitude: -80.1918,
  },
  {
    name: 'EUA – Orlando',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    language: 'Inglês',
    currency: 'USD (Dólar Americano)',
    voltage: '120V',
    timezone_offset: -2,
    best_season: 'Outubro a Maio',
    visa_required: true,
    visa_info: 'Visto B1/B2 obrigatório',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Visto americano'],
    latitude: 28.5383,
    longitude: -81.3792,
  },
  {
    name: 'EUA – Los Angeles',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    language: 'Inglês',
    currency: 'USD (Dólar Americano)',
    voltage: '120V',
    timezone_offset: -5,
    best_season: 'Maio a Outubro',
    visa_required: true,
    visa_info: 'Visto B1/B2 obrigatório',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Visto americano'],
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    name: 'EUA – Las Vegas',
    country: 'Estados Unidos',
    capital: 'Washington D.C.',
    language: 'Inglês',
    currency: 'USD (Dólar Americano)',
    voltage: '120V',
    timezone_offset: -5,
    best_season: 'Outubro a Maio',
    visa_required: true,
    visa_info: 'Visto B1/B2 obrigatório',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Visto americano'],
    latitude: 36.1699,
    longitude: -115.1398,
  },
  // ===== CANADÁ =====
  {
    name: 'Canadá – Toronto',
    country: 'Canadá',
    capital: 'Ottawa',
    language: 'Inglês / Francês',
    currency: 'CAD (Dólar Canadense)',
    voltage: '120V',
    timezone_offset: -2,
    best_season: 'Maio a Setembro',
    visa_required: true,
    visa_info: 'Visto eTA ou visto de turista obrigatório',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'eTA ou Visto canadense'],
    latitude: 43.6532,
    longitude: -79.3832,
  },
  // ===== CUBA =====
  {
    name: 'Cuba – Havana',
    country: 'Cuba',
    capital: 'Havana',
    language: 'Espanhol',
    currency: 'CUP (Peso Cubano)',
    voltage: '110V / 220V',
    timezone_offset: -3,
    best_season: 'Novembro a Abril',
    visa_required: true,
    visa_info: 'Tarjeta do Turista obrigatória (comprada na chegada ou online)',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Tarjeta del Turista', 'Seguro de saúde obrigatório'],
    latitude: 23.1136,
    longitude: -82.3666,
  },
  // ===== URUGUAI =====
  {
    name: 'Uruguai – Montevidéu',
    country: 'Uruguai',
    capital: 'Montevidéu',
    language: 'Espanhol',
    currency: 'UYU (Peso Uruguaio)',
    voltage: '220V',
    timezone_offset: 0,
    best_season: 'Dezembro a Março',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto',
    vaccines: [],
    documents_needed: ['RG ou Passaporte'],
    latitude: -34.9011,
    longitude: -56.1645,
  },
  // ===== PORTUGAL =====
  {
    name: 'Portugal – Lisboa',
    country: 'Portugal',
    capital: 'Lisboa',
    language: 'Português',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Março a Outubro',
    visa_required: false,
    visa_info: 'Brasileiro no Espaço Schengen pode ficar até 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Seguro de viagem (recomendado)'],
    latitude: 38.7223,
    longitude: -9.1393,
  },
  {
    name: 'Portugal – Porto',
    country: 'Portugal',
    capital: 'Lisboa',
    language: 'Português',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Abril a Setembro',
    visa_required: false,
    visa_info: 'Brasileiro no Espaço Schengen pode ficar até 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 41.1579,
    longitude: -8.6291,
  },
  // ===== ESPANHA =====
  {
    name: 'Espanha – Madrid',
    country: 'Espanha',
    capital: 'Madrid',
    language: 'Espanhol',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Abril a Junho / Setembro a Novembro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 40.4168,
    longitude: -3.7038,
  },
  {
    name: 'Espanha – Barcelona',
    country: 'Espanha',
    capital: 'Madrid',
    language: 'Espanhol / Catalão',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Maio a Outubro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 41.3851,
    longitude: 2.1734,
  },
  // ===== FRANÇA =====
  {
    name: 'França – Paris',
    country: 'França',
    capital: 'Paris',
    language: 'Francês',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Abril a Junho / Setembro a Outubro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 48.8566,
    longitude: 2.3522,
  },
  // ===== ITÁLIA =====
  {
    name: 'Itália – Roma',
    country: 'Itália',
    capital: 'Roma',
    language: 'Italiano',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Abril a Junho / Setembro a Outubro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 41.9028,
    longitude: 12.4964,
  },
  // ===== INGLATERRA =====
  {
    name: 'Inglaterra – Londres',
    country: 'Reino Unido',
    capital: 'Londres',
    language: 'Inglês',
    currency: 'GBP (Libra Esterlina)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Maio a Setembro',
    visa_required: true,
    visa_info: 'Visto de turista obrigatório (Electronic Travel Authorisation – ETA)',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'ETA / Visto britânico'],
    latitude: 51.5074,
    longitude: -0.1278,
  },
  // ===== ALEMANHA =====
  {
    name: 'Alemanha – Berlim',
    country: 'Alemanha',
    capital: 'Berlim',
    language: 'Alemão',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Maio a Setembro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 52.52,
    longitude: 13.405,
  },
  // ===== HOLANDA =====
  {
    name: 'Holanda – Amsterdã',
    country: 'Países Baixos',
    capital: 'Amsterdã',
    language: 'Holandês',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Abril a Setembro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 52.3676,
    longitude: 4.9041,
  },
  // ===== GRÉCIA =====
  {
    name: 'Grécia – Santorini / Atenas',
    country: 'Grécia',
    capital: 'Atenas',
    language: 'Grego',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Maio a Outubro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 36.3932,
    longitude: 25.4615,
  },
  // ===== SUÍÇA =====
  {
    name: 'Suíça – Zurique / Interlaken',
    country: 'Suíça',
    capital: 'Berna',
    language: 'Alemão / Francês / Italiano',
    currency: 'CHF (Franco Suíço)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Junho a Setembro / Dezembro a Março (esqui)',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 46.818,
    longitude: 8.2275,
  },
  // ===== ÁUSTRIA =====
  {
    name: 'Áustria – Viena',
    country: 'Áustria',
    capital: 'Viena',
    language: 'Alemão',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Abril a Outubro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 48.2082,
    longitude: 16.3738,
  },
  // ===== IRLANDA =====
  {
    name: 'Irlanda – Dublin',
    country: 'Irlanda',
    capital: 'Dublin',
    language: 'Inglês / Irlandês',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Maio a Setembro',
    visa_required: false,
    visa_info: 'Brasileiro pode ficar até 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 53.3498,
    longitude: -6.2603,
  },
  // ===== CROÁCIA =====
  {
    name: 'Croácia – Dubrovnik / Split',
    country: 'Croácia',
    capital: 'Zagreb',
    language: 'Croata',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Maio a Setembro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 42.6507,
    longitude: 18.0944,
  },
  // ===== REPÚBLICA TCHECA =====
  {
    name: 'República Tcheca – Praga',
    country: 'República Tcheca',
    capital: 'Praga',
    language: 'Tcheco',
    currency: 'CZK (Coroa Tcheca)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Abril a Outubro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 50.0755,
    longitude: 14.4378,
  },
  // ===== TURQUIA =====
  {
    name: 'Turquia – Istambul / Capadócia',
    country: 'Turquia',
    capital: 'Ancara',
    language: 'Turco',
    currency: 'TRY (Lira Turca)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Abril a Junho / Setembro a Novembro',
    visa_required: true,
    visa_info: 'e-Visto obrigatório – solicitar online antes da viagem',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'e-Visto turco'],
    latitude: 41.0082,
    longitude: 28.9784,
  },
  // ===== NORUEGA =====
  {
    name: 'Noruega – Oslo / Fjords',
    country: 'Noruega',
    capital: 'Oslo',
    language: 'Norueguês',
    currency: 'NOK (Coroa Norueguesa)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Junho a Agosto',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 59.9139,
    longitude: 10.7522,
  },
  // ===== ISLÂNDIA =====
  {
    name: 'Islândia – Reykjavík',
    country: 'Islândia',
    capital: 'Reykjavík',
    language: 'Islandês',
    currency: 'ISK (Coroa Islandesa)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Junho a Agosto (Aurora: Outubro a Março)',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 64.1466,
    longitude: -21.9426,
  },
  // ===== BÉLGICA =====
  {
    name: 'Bélgica – Bruxelas',
    country: 'Bélgica',
    capital: 'Bruxelas',
    language: 'Holandês / Francês / Alemão',
    currency: 'EUR (Euro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Maio a Setembro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 50.8503,
    longitude: 4.3517,
  },
  // ===== HUNGRIA =====
  {
    name: 'Hungria – Budapeste',
    country: 'Hungria',
    capital: 'Budapeste',
    language: 'Húngaro',
    currency: 'HUF (Florim Húngaro)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Abril a Outubro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 47.4979,
    longitude: 19.0402,
  },
  // ===== POLÔNIA =====
  {
    name: 'Polônia – Cracóvia / Varsóvia',
    country: 'Polônia',
    capital: 'Varsóvia',
    language: 'Polonês',
    currency: 'PLN (Zloty)',
    voltage: '230V',
    timezone_offset: -5,
    best_season: 'Maio a Setembro',
    visa_required: false,
    visa_info: 'Espaço Schengen – 90 dias sem visto',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 50.0647,
    longitude: 19.945,
  },
  // ===== JAPÃO =====
  {
    name: 'Japão – Tóquio / Kyoto',
    country: 'Japão',
    capital: 'Tóquio',
    language: 'Japonês',
    currency: 'JPY (Iene Japonês)',
    voltage: '100V',
    timezone_offset: 12,
    best_season: 'Março a Maio / Setembro a Novembro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 90 dias)',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'Comprovante de hospedagem', 'Comprovante financeiro'],
    latitude: 35.6762,
    longitude: 139.6503,
  },
  // ===== TAILÂNDIA =====
  {
    name: 'Tailândia – Bangkok / Phuket',
    country: 'Tailândia',
    capital: 'Bangkok',
    language: 'Tailandês',
    currency: 'THB (Baht Tailandês)',
    voltage: '220V',
    timezone_offset: 10,
    best_season: 'Novembro a Abril',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 30 dias)',
    vaccines: ['Hepatite A', 'Hepatite B', 'Febre Tifóide', 'Febre Amarela (se vindo de área endêmica)'],
    documents_needed: ['Passaporte válido'],
    latitude: 15.87,
    longitude: 100.9925,
  },
  // ===== INDONÉSIA / BALI =====
  {
    name: 'Indonésia – Bali',
    country: 'Indonésia',
    capital: 'Jacarta',
    language: 'Indonésio / Balinês',
    currency: 'IDR (Rupia Indonésia)',
    voltage: '230V',
    timezone_offset: 12,
    best_season: 'Abril a Outubro',
    visa_required: true,
    visa_info: 'Visa on Arrival disponível (USD 35) ou e-Visa online',
    vaccines: ['Hepatite A', 'Hepatite B', 'Febre Tifóide', 'Raiva (se contato com animais)'],
    documents_needed: ['Passaporte válido (mínimo 6 meses)', 'Passagem de volta', 'Visa on Arrival'],
    latitude: -8.4095,
    longitude: 115.1889,
  },
  // ===== VIETNÃ =====
  {
    name: 'Vietnã – Hanói / Hoi An',
    country: 'Vietnã',
    capital: 'Hanói',
    language: 'Vietnamita',
    currency: 'VND (Dong Vietnamita)',
    voltage: '220V',
    timezone_offset: 12,
    best_season: 'Novembro a Abril',
    visa_required: true,
    visa_info: 'e-Visa necessário – solicitar online antes da viagem',
    vaccines: ['Hepatite A', 'Hepatite B', 'Febre Tifóide'],
    documents_needed: ['Passaporte válido', 'e-Visa vietnamita'],
    latitude: 14.0583,
    longitude: 108.2772,
  },
  // ===== ÍNDIA =====
  {
    name: 'Índia – Goa / Rajastão',
    country: 'Índia',
    capital: 'Nova Délhi',
    language: 'Hindi / Inglês',
    currency: 'INR (Rupia Indiana)',
    voltage: '230V',
    timezone_offset: 8.5,
    best_season: 'Outubro a Março',
    visa_required: true,
    visa_info: 'e-Visa obrigatório – solicitar online antes da viagem',
    vaccines: ['Hepatite A', 'Hepatite B', 'Febre Tifóide', 'Febre Amarela (se vindo de área endêmica)'],
    documents_needed: ['Passaporte válido', 'e-Visa indiano'],
    latitude: 20.5937,
    longitude: 78.9629,
  },
  // ===== COREIA DO SUL =====
  {
    name: 'Coreia do Sul – Seoul',
    country: 'Coreia do Sul',
    capital: 'Seoul',
    language: 'Coreano',
    currency: 'KRW (Won Sul-Coreano)',
    voltage: '220V',
    timezone_offset: 12,
    best_season: 'Março a Maio / Setembro a Novembro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 90 dias)',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'K-ETA (autorização eletrônica)'],
    latitude: 37.5665,
    longitude: 126.978,
  },
  // ===== SINGAPURA =====
  {
    name: 'Singapura',
    country: 'Singapura',
    capital: 'Singapura',
    language: 'Inglês / Mandarim / Malaio / Tamil',
    currency: 'SGD (Dólar de Singapura)',
    voltage: '230V',
    timezone_offset: 11,
    best_season: 'Fevereiro a Abril / Julho a Setembro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 30 dias)',
    vaccines: ['Febre Amarela (obrigatória se vindo de área endêmica)'],
    documents_needed: ['Passaporte válido'],
    latitude: 1.3521,
    longitude: 103.8198,
  },
  // ===== DUBAI / EAU =====
  {
    name: 'Dubai – Emirados Árabes Unidos',
    country: 'Emirados Árabes Unidos',
    capital: 'Abu Dhabi',
    language: 'Árabe / Inglês',
    currency: 'AED (Dirham dos EAU)',
    voltage: '220V',
    timezone_offset: 7,
    best_season: 'Outubro a Abril',
    visa_required: false,
    visa_info: 'Brasileiro recebe visto na chegada gratuitamente (30 dias)',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 25.2048,
    longitude: 55.2708,
  },
  // ===== ISRAEL =====
  {
    name: 'Israel – Tel Aviv / Jerusalém',
    country: 'Israel',
    capital: 'Jerusalém',
    language: 'Hebraico / Árabe',
    currency: 'ILS (Novo Shekel Israelense)',
    voltage: '230V',
    timezone_offset: -4,
    best_season: 'Março a Maio / Setembro a Novembro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 90 dias)',
    vaccines: [],
    documents_needed: ['Passaporte válido'],
    latitude: 31.0461,
    longitude: 34.8516,
  },
  // ===== MALDIVAS =====
  {
    name: 'Maldivas',
    country: 'Maldivas',
    capital: 'Malé',
    language: 'Dhivehi / Inglês',
    currency: 'MVR (Rufiyaa das Maldivas)',
    voltage: '230V',
    timezone_offset: 9,
    best_season: 'Novembro a Abril',
    visa_required: false,
    visa_info: 'Visto de turista gratuito na chegada (30 dias)',
    vaccines: ['Febre Amarela (obrigatória se vindo de área endêmica)'],
    documents_needed: ['Passaporte válido', 'Reserva de hotel confirmada'],
    latitude: 3.2028,
    longitude: 73.2207,
  },
  // ===== MARROCOS =====
  {
    name: 'Marrocos – Marrakech',
    country: 'Marrocos',
    capital: 'Rabat',
    language: 'Árabe / Berbere / Francês',
    currency: 'MAD (Dirham Marroquino)',
    voltage: '220V',
    timezone_offset: -3,
    best_season: 'Março a Maio / Setembro a Novembro',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 90 dias)',
    vaccines: ['Hepatite A', 'Hepatite B', 'Febre Tifóide'],
    documents_needed: ['Passaporte válido'],
    latitude: 31.6295,
    longitude: -7.9811,
  },
  // ===== EGITO =====
  {
    name: 'Egito – Cairo / Luxor',
    country: 'Egito',
    capital: 'Cairo',
    language: 'Árabe',
    currency: 'EGP (Libra Egípcia)',
    voltage: '220V',
    timezone_offset: -2,
    best_season: 'Outubro a Abril',
    visa_required: true,
    visa_info: 'e-Visa obrigatório – solicitar online antes da viagem',
    vaccines: ['Hepatite A', 'Hepatite B', 'Febre Tifóide', 'Febre Amarela (se vindo de área endêmica)'],
    documents_needed: ['Passaporte válido', 'e-Visa egípcio'],
    latitude: 26.8206,
    longitude: 30.8025,
  },
  // ===== ÁFRICA DO SUL =====
  {
    name: 'África do Sul – Cidade do Cabo',
    country: 'África do Sul',
    capital: 'Pretória / Cidade do Cabo',
    language: 'Inglês / Afrikaans / Zulu',
    currency: 'ZAR (Rand Sul-Africano)',
    voltage: '230V',
    timezone_offset: -2,
    best_season: 'Outubro a Abril',
    visa_required: false,
    visa_info: 'Brasileiro não precisa de visto (até 30 dias)',
    vaccines: ['Febre Amarela (obrigatória se vindo de área endêmica)', 'Malária (profilaxia recomendada em algumas regiões)'],
    documents_needed: ['Passaporte válido'],
    latitude: -33.9249,
    longitude: 18.4241,
  },
  // ===== AUSTRÁLIA =====
  {
    name: 'Austrália – Sydney / Melbourne',
    country: 'Austrália',
    capital: 'Canberra',
    language: 'Inglês',
    currency: 'AUD (Dólar Australiano)',
    voltage: '230V',
    timezone_offset: 13,
    best_season: 'Setembro a Novembro / Março a Maio',
    visa_required: true,
    visa_info: 'eVisitor (subclasse 651) obrigatório – gratuito, solicitar online',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'eVisitor australiano'],
    latitude: -25.2744,
    longitude: 133.7751,
  },
  // ===== NOVA ZELÂNDIA =====
  {
    name: 'Nova Zelândia – Auckland / Queenstown',
    country: 'Nova Zelândia',
    capital: 'Wellington',
    language: 'Inglês / Maori',
    currency: 'NZD (Dólar Neozelandês)',
    voltage: '230V',
    timezone_offset: 15,
    best_season: 'Novembro a Março',
    visa_required: true,
    visa_info: 'NZeTA (Electronic Travel Authority) obrigatória – solicitar online',
    vaccines: [],
    documents_needed: ['Passaporte válido', 'NZeTA neozelandesa'],
    latitude: -40.9006,
    longitude: 174.886,
  },
]

export function getDestinationByName(name: string): Destination | undefined {
  return DESTINATIONS.find(
    (d) => d.name.toLowerCase().includes(name.toLowerCase()) ||
           d.country.toLowerCase().includes(name.toLowerCase())
  )
}
